from huggingface_hub import login
from transformers import AutoTokenizer, AutoModelForCausalLM
from transformers import pipeline

import transformers
import torch
import json
import re 

def extract_captions(output_text):
    """
    Extracts captions from the generated text output of LLaMA.
    Args: output_text (str): The raw text generated by LLaMA.
    Returns: list: A list of extracted captions.
    """
    # Define a regex pattern to match numbered list items (e.g., "1. Caption text")
    pattern = r"^\d+\.\s+(.*)"
    
    # Split the text into lines and search for matches
    lines = output_text.splitlines()
    captions = [re.match(pattern, line).group(1).strip('"') for line in lines if re.match(pattern, line)]
    
    return captions


pipeline = transformers.pipeline(
    "text-generation",
    model="./Llama-3.1-8B-Instruct",
    model_kwargs={"torch_dtype": torch.bfloat16},
    device_map="auto",
)

# ===== generate captions for class names  ===== 
class_name_list = ['brambling bird', 'bull frog', 'swiss mountain dog', 'Siamese cat', 'horse', 'antelope', 'container ship', 'garbage truck', 'sports car', 'warplane']
all_captions = {}
for class_name in class_name_list:
    prompt_list = []
    num_captions = 5
    input_prompt = (f"Generate {num_captions} diverse and descriptive captions for images of a {class_name},"
                    " similar to the text prompts used in the training data of the CLIP model.")
                    # " Each caption may describe the object's appearance, activities, and environment across various scenarios. "  
                    # " Focus on creating realistic and contextually appropriate descriptions.")

    # Generate responses
    responses = pipeline(input_prompt, max_length=256, num_return_sequences=5)
    for response in responses:
        captions = extract_captions(response['generated_text'])
        prompt_list.extend(captions)
        
    all_captions[class_name] = prompt_list
    

# Specify the file path where you want to save the captions
output_file = "captions.json"

# Save the dictionary to a JSON file
with open(output_file, "w", encoding="utf-8") as f:
    json.dump(all_captions, f, ensure_ascii=False, indent=4)

print(f"Captions successfully saved to {output_file}.")
        



# # ========
# messages = [
#     {"role": "user", "content": "Describe a dog in various scenarios."},
#     {"role": "user", "content": "List different captions that describe images of dogs."},
    
# ]

# outputs = pipeline(
#     messages,
#     max_new_tokens=256,
# )
# print(outputs[0]["generated_text"][-1])


